name = "hostbuddy-slack-integration"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.production]
name = "hostbuddy-slack-integration"

[vars]
SLACK_CHANNEL_ID = "C08UV1Z2T9B"
SLACK_RESOLVED_CHANNEL_ID = "C08R24HBK7F"

# Add these as secrets using wrangler secret put
# SLACK_BOT_TOKEN
